"""Initial models for appointment management

Revision ID: b812fed158ab
Revises: 0d6e21037283
Create Date: 2024-11-22 22:54:06.387998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b812fed158ab'
down_revision: Union[str, None] = '0d6e21037283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('is_qualified', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zillow_id', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('square_feet', sa.Integer(), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'SOLD', 'OFF_MARKET', name='propertystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zillow_id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('appointment_type', sa.Enum('IN_PERSON', 'VIDEO', name='appointmenttype'), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='appointmentstatus'), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('fallback_property_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['fallback_property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('min_bedrooms', sa.Integer(), nullable=True),
    sa.Column('min_bathrooms', sa.Float(), nullable=True),
    sa.Column('min_square_feet', sa.Integer(), nullable=True),
    sa.Column('preferred_zip_codes', sa.JSON(), nullable=True),
    sa.Column('preferred_cities', sa.JSON(), nullable=True),
    sa.Column('property_types', sa.JSON(), nullable=True),
    sa.Column('search_radius', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_transcript_analyses_id', table_name='transcript_analyses')
    op.drop_table('transcript_analyses')
    op.drop_index('ix_calls_agent_id', table_name='calls')
    op.drop_index('ix_calls_id', table_name='calls')
    op.drop_table('calls')
    op.drop_index('ix_call_metrics_id', table_name='call_metrics')
    op.drop_table('call_metrics')
    op.drop_index('ix_action_items_id', table_name='action_items')
    op.drop_table('action_items')
    op.drop_index('ix_scripts_category', table_name='scripts')
    op.drop_index('ix_scripts_id', table_name='scripts')
    op.drop_table('scripts')
    op.drop_index('ix_transcripts_id', table_name='transcripts')
    op.drop_table('transcripts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcripts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('call_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('speaker', sa.VARCHAR(), nullable=True),
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transcripts_id', 'transcripts', ['id'], unique=False)
    op.create_table('scripts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('trigger_words', sqlite.JSON(), nullable=True),
    sa.Column('context', sqlite.JSON(), nullable=True),
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.Column('variations', sqlite.JSON(), nullable=True),
    sa.Column('success_rate', sa.FLOAT(), nullable=True),
    sa.Column('usage_count', sa.INTEGER(), nullable=True),
    sa.Column('last_used', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scripts_id', 'scripts', ['id'], unique=False)
    op.create_index('ix_scripts_category', 'scripts', ['category'], unique=False)
    op.create_table('action_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('call_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('priority', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('action_type', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_action_items_id', 'action_items', ['id'], unique=False)
    op.create_table('call_metrics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('call_id', sa.INTEGER(), nullable=True),
    sa.Column('appointment_progress', sa.FLOAT(), nullable=True),
    sa.Column('location_progress', sa.FLOAT(), nullable=True),
    sa.Column('motivation_progress', sa.FLOAT(), nullable=True),
    sa.Column('rapport_score', sa.FLOAT(), nullable=True),
    sa.Column('talk_ratio', sa.FLOAT(), nullable=True),
    sa.Column('interruption_count', sa.INTEGER(), nullable=True),
    sa.Column('question_count', sa.INTEGER(), nullable=True),
    sa.Column('contact_info_captured', sa.BOOLEAN(), nullable=True),
    sa.Column('budget_discussed', sa.BOOLEAN(), nullable=True),
    sa.Column('timeline_established', sa.BOOLEAN(), nullable=True),
    sa.Column('preferences_noted', sa.BOOLEAN(), nullable=True),
    sa.Column('objections_raised', sa.INTEGER(), nullable=True),
    sa.Column('objections_handled', sa.INTEGER(), nullable=True),
    sa.Column('appointment_set', sa.BOOLEAN(), nullable=True),
    sa.Column('follow_up_scheduled', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_index('ix_call_metrics_id', 'call_metrics', ['id'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('agent_id', sa.VARCHAR(), nullable=True),
    sa.Column('lead_phone', sa.VARCHAR(), nullable=True),
    sa.Column('lead_name', sa.VARCHAR(), nullable=True),
    sa.Column('property_address', sa.VARCHAR(), nullable=True),
    sa.Column('call_duration', sa.INTEGER(), nullable=True),
    sa.Column('call_status', sa.VARCHAR(), nullable=True),
    sa.Column('success_rating', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calls_id', 'calls', ['id'], unique=False)
    op.create_index('ix_calls_agent_id', 'calls', ['agent_id'], unique=False)
    op.create_table('transcript_analyses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('transcript_id', sa.INTEGER(), nullable=True),
    sa.Column('sentiment_score', sa.FLOAT(), nullable=True),
    sa.Column('intent', sa.VARCHAR(), nullable=True),
    sa.Column('entities', sqlite.JSON(), nullable=True),
    sa.Column('key_points', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transcript_analyses_id', 'transcript_analyses', ['id'], unique=False)
    op.drop_table('search_preferences')
    op.drop_table('appointments')
    op.drop_table('properties')
    op.drop_table('clients')
    # ### end Alembic commands ###
